use rustycord::{
    Client,
};

// I highly recommend enabling logger
// to recieve logs generated by rustycord

#[macro_use]
extern crate log;

#[tokio::main]
async fn main() {
    // Init env_logger, you can use other implementations too
    env_logger::init();

    // For application level logs
    info!("Starting up..");
    
    Client::builder()
        .token("TOKEN")
        .build()
        .run()
        .await;
}

// If this doesn't work, check your `RUST_LOG` environment variable
